import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import clsx from "clsx";
import "./globals.css";

import NextAuthProvider from "@/providers/NextAuthProvider";
import ModalProvider from "@/contexts/ModalContext";
import TaskProvider from "@/contexts/TaskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-gray-50")}>
        <NextAuthProvider>
          <TaskProvider>
            <ModalProvider>
              <Toaster />
              {children}
            </ModalProvider>
          </TaskProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
