import clsx from "clsx";
import "./globals.css";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-gray-100")}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
